## view, reshape
객체의 배열을 재구성합니다.
reshape은 size 함수의 순서대로 각 차원에 들어갈 객체의 개수를 넣습니다.  
-1을 넣으면 그 값을 원래 배열의 길이와 남은 차원으로 추정합니다.

In [18]:
# 첫번째 = number of batches
# 두번째 = 행(number of tokens)
# 세번째 = 열(number of dimension)

import torch
example = torch.tensor([[[1,2,3],[1,2,3]]])
print(example)
print("변환 전:", example.shape)

example = example.reshape(1,3,2)

print("\n",example)
print("변환 후:", example.shape)

example = example.reshape(1,-1,2)

print("\n",example)
print("변환 후:", example.shape)

example = example.reshape(1,6,-1)

print("\n",example)
print("변환 후:", example.shape)

tensor([[[1, 2, 3],
         [1, 2, 3]]])
변환 전: torch.Size([1, 2, 3])

 tensor([[[1, 2],
         [3, 1],
         [2, 3]]])
변환 후: torch.Size([1, 3, 2])

 tensor([[[1, 2],
         [3, 1],
         [2, 3]]])
변환 후: torch.Size([1, 3, 2])

 tensor([[[1],
         [2],
         [3],
         [1],
         [2],
         [3]]])
변환 후: torch.Size([1, 6, 1])


In [19]:
# 첫번째 = number of batches
# 두번째 = 행(number of tokens)
# 세번째 = 열(number of dimension)

import torch
example = torch.tensor([[[1,2,3],[1,2,3]]])
print(example)
print("변환 전:", example.shape)

example = example.view(1,3,2)

print("\n",example)
print("변환 후:", example.shape)

example = example.view(1,-1,2)

print("\n",example)
print("변환 후:", example.shape)

example = example.view(1,6,-1)

print("\n",example)
print("변환 후:", example.shape)

tensor([[[1, 2, 3],
         [1, 2, 3]]])
변환 전: torch.Size([1, 2, 3])

 tensor([[[1, 2],
         [3, 1],
         [2, 3]]])
변환 후: torch.Size([1, 3, 2])

 tensor([[[1, 2],
         [3, 1],
         [2, 3]]])
변환 후: torch.Size([1, 3, 2])

 tensor([[[1],
         [2],
         [3],
         [1],
         [2],
         [3]]])
변환 후: torch.Size([1, 6, 1])
