## squeeze, unsqueeze
차원의 size를 조절합니다. 1인 차원을 원하는 곳에 추가하거나 줄일 수 있습니다.

In [3]:
import torch

a = torch.tensor([[1,2,3],[2,2,1],[3,7,7]])

In [29]:
b = a.unsqueeze(0)

print(b,b.size())

b = a.unsqueeze(1)

print("\n", b, b.size())

b = a.unsqueeze(2)

print("\n",b, b.size())

tensor([[[[1, 2],
          [3, 7],
          [5, 6]]]]) torch.Size([1, 1, 3, 2])

 tensor([[[[1, 2],
          [3, 7],
          [5, 6]]]]) torch.Size([1, 1, 3, 2])

 tensor([[[[1, 2]],

         [[3, 7]],

         [[5, 6]]]]) torch.Size([1, 3, 1, 2])


In [32]:
# 차원이 1이 아닌 차원을 squeeze할 경우 아무 일도 일어나지 않습니다.
a = torch.tensor([[[1,2],[3,7],[5,6]]])
print(a.size())

b = a.squeeze(0)
print(b, b.size())

b = a.squeeze(1)
print(b, b.size())

b = a.squeeze(2)
print(b, b.size())

torch.Size([1, 3, 2])
tensor([[1, 2],
        [3, 7],
        [5, 6]]) torch.Size([3, 2])
tensor([[[1, 2],
         [3, 7],
         [5, 6]]]) torch.Size([1, 3, 2])
tensor([[[1, 2],
         [3, 7],
         [5, 6]]]) torch.Size([1, 3, 2])


In [36]:
a = torch.tensor([[[1],[3],[5]]])
print(a.size())

b = a.squeeze(0)
print(b, b.size())

b = a.squeeze(1)
print(b, b.size())

b = a.squeeze(2)
print(b, b.size())

torch.Size([1, 3, 1])
tensor([[1],
        [3],
        [5]]) torch.Size([3, 1])
tensor([[[1],
         [3],
         [5]]]) torch.Size([1, 3, 1])
tensor([[1, 3, 5]]) torch.Size([1, 3])
